# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "**"
jobs:
  create_release:
    name: Create Github release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true

  build:
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64, arm, mips, mips64, mips64le, mipsle, ppc64, ppc64le, riscv64, s390x, 386]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1.51
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # A default variable that allows adding files to Release
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.21.1 # You can specify the version of Golang to use for compilation
        binary_name: "hide.me" # You can specify the name of the binary
        extra_files: hide.me@.service CA.pem install.sh uninstall.sh README.md LICENSE.md
        ldflags: -s -w
